package gfx;

import java.awt.image.BufferedImage;

public class Assets {
	
	public static BufferedImage title;
    public static BufferedImage maze;
    public static BufferedImage wMaze;
    public static BufferedImage dot;
    public static BufferedImage powerPellet;
    public static BufferedImage pacman0;
    public static BufferedImage pacman1U;
    public static BufferedImage pacman2U;
    public static BufferedImage pacman1D;
    public static BufferedImage pacman2D;
    public static BufferedImage pacman1L;
    public static BufferedImage pacman2L;
    public static BufferedImage pacman1R;
    public static BufferedImage pacman2R;
    public static BufferedImage pacmanDeath1;
    public static BufferedImage pacmanDeath2;
    public static BufferedImage pacmanDeath3;
    public static BufferedImage pacmanDeath4;
    public static BufferedImage pacmanDeath5;
    public static BufferedImage pacmanDeath6;
    public static BufferedImage pacmanDeath7;
    public static BufferedImage pacmanDeath8;
    public static BufferedImage pacmanDeath9;
    public static BufferedImage pacmanDeath10;
    public static BufferedImage pacmanDeath11;
    public static BufferedImage blinky1U;
    public static BufferedImage blinky2U;
    public static BufferedImage blinky1D;
    public static BufferedImage blinky2D;
    public static BufferedImage blinky1L;
    public static BufferedImage blinky2L;
    public static BufferedImage blinky1R;
    public static BufferedImage blinky2R;
    public static BufferedImage pinky1U;
    public static BufferedImage pinky2U;
    public static BufferedImage pinky1D;
    public static BufferedImage pinky2D;
    public static BufferedImage pinky1L;
    public static BufferedImage pinky2L;
    public static BufferedImage pinky1R;
    public static BufferedImage pinky2R;
    public static BufferedImage inky1U;
    public static BufferedImage inky2U;
    public static BufferedImage inky1D;
    public static BufferedImage inky2D;
    public static BufferedImage inky1L;
    public static BufferedImage inky2L;
    public static BufferedImage inky1R;
    public static BufferedImage inky2R;
    public static BufferedImage clyde1U;
    public static BufferedImage clyde2U;
    public static BufferedImage clyde1D;
    public static BufferedImage clyde2D;
    public static BufferedImage clyde1L;
    public static BufferedImage clyde2L;
    public static BufferedImage clyde1R;
    public static BufferedImage clyde2R;
    public static BufferedImage freightened1B;
    public static BufferedImage freightened2B;
    public static BufferedImage freightened1W;
    public static BufferedImage freightened2W;
    public static BufferedImage[] pacmanU = new BufferedImage[3];
    public static BufferedImage[] pacmanD = new BufferedImage[3];
    public static BufferedImage[] pacmanL = new BufferedImage[3];
    public static BufferedImage[] pacmanR = new BufferedImage[3];
    public static BufferedImage[] pacmanDeath = new BufferedImage[11];
    public static BufferedImage[] blinkyU = new BufferedImage[2];
    public static BufferedImage[] blinkyD = new BufferedImage[2];
    public static BufferedImage[] blinkyL = new BufferedImage[2];
    public static BufferedImage[] blinkyR = new BufferedImage[2];
    public static BufferedImage[] pinkyU = new BufferedImage[2];
    public static BufferedImage[] pinkyD = new BufferedImage[2];
    public static BufferedImage[] pinkyL = new BufferedImage[2];
    public static BufferedImage[] pinkyR = new BufferedImage[2];
    public static BufferedImage[] inkyU = new BufferedImage[2];
    public static BufferedImage[] inkyD = new BufferedImage[2];
    public static BufferedImage[] inkyL = new BufferedImage[2];
    public static BufferedImage[] inkyR = new BufferedImage[2];
    public static BufferedImage[] clydeU = new BufferedImage[2];
    public static BufferedImage[] clydeD = new BufferedImage[2];
    public static BufferedImage[] clydeL = new BufferedImage[2];
    public static BufferedImage[] clydeR = new BufferedImage[2];
    public static BufferedImage[] freightenedB = new BufferedImage[2];
    public static BufferedImage[] freightenedBW = new BufferedImage[4];
    public static BufferedImage eatenU;
    public static BufferedImage eatenD;
    public static BufferedImage eatenL;
    public static BufferedImage eatenR;
    public static BufferedImage zero;
    public static BufferedImage one;
    public static BufferedImage two;
    public static BufferedImage three;
    public static BufferedImage four;
    public static BufferedImage five;
    public static BufferedImage six;
    public static BufferedImage seven;
    public static BufferedImage eight;
    public static BufferedImage nine;
    public static BufferedImage twoHundred;
    public static BufferedImage fourHundred;
    public static BufferedImage eightHundred;
    public static BufferedImage sixteenHundred;
    public static BufferedImage lives;
    public static BufferedImage cherry;
    public static BufferedImage strawberry;
    public static BufferedImage peach;
    public static BufferedImage apple;
    public static BufferedImage grapes;
    public static BufferedImage galaxian;
    public static BufferedImage bell;
    public static BufferedImage key;
    public static BufferedImage oneHundred;
    public static BufferedImage threeHundred;
    public static BufferedImage fiveHundred;
    public static BufferedImage sevenHundred;
    public static BufferedImage oneThousand;
    public static BufferedImage twoThousand;
    public static BufferedImage threeThousand;
    public static BufferedImage fiveThousand;
    public static BufferedImage[] fruits = new BufferedImage[13];
    public static BufferedImage[] fruitsScores = new BufferedImage[13];
    public static BufferedImage ready;
    public static BufferedImage gameOver;
    public static BufferedImage a;
    public static BufferedImage b;
    public static BufferedImage c;
    public static BufferedImage d;
    public static BufferedImage e;
    public static BufferedImage f;
    public static BufferedImage g;
    public static BufferedImage h;
    public static BufferedImage i;
    public static BufferedImage j;
    public static BufferedImage k;
    public static BufferedImage l;
    public static BufferedImage m;
    public static BufferedImage n;
    public static BufferedImage o;
    public static BufferedImage p;
    public static BufferedImage q;
    public static BufferedImage r;
    public static BufferedImage s;
    public static BufferedImage t;
    public static BufferedImage u;
    public static BufferedImage v;
    public static BufferedImage w;
    public static BufferedImage x;
    public static BufferedImage y;
    public static BufferedImage z;
    public static BufferedImage pointer;
    public static BufferedImage redPointer;

    public static int n0 = 39;
    public static int n1 = 48;
    public static int n2 = 24;
    public static int n3 = 64;
    public static int n4 = 9;

    public static void init() {
        SpriteSheet sheet = new SpriteSheet(ImageLoader.loadImage("/textures/GeneralSprites.png"));
        SpriteSheet sheet2 = new SpriteSheet(ImageLoader.loadImage("/textures/CompleteMaze.png"));
        SpriteSheet sheet3 = new SpriteSheet(ImageLoader.loadImage("/textures/Letters.png"));
        SpriteSheet sheet4 = new SpriteSheet(ImageLoader.loadImage("/textures/WhiteMaze.png"));
        
        title = sheet3.crop(2, 4, 182, 46);
        
        maze = sheet2.crop(684, 0, 672, 744);
        wMaze = sheet4.crop(684, 0, 672, 744);

        dot = sheet.crop(3, 572, n2, n2);
        powerPellet = sheet.crop(3, 543, n2, n2);

        pacman0 = sheet.crop(126, 6, n0, n0);
        pacman1U = sheet.crop(6, 126, n0, n0);
        pacman2U = sheet.crop(66, 126, n0, n0);
        pacman1D = sheet.crop(6, 186, n0, n0);
        pacman2D = sheet.crop(66, 183, n0, n0);
        pacman1L = sheet.crop(6, 6, n0, n0);
        pacman2L = sheet.crop(66, 6, n0, n0);
        pacman1R = sheet.crop(6, 66, n0, n0);
        pacman2R = sheet.crop(66, 66, n0, n0);
        pacmanU[0] = pacman0;
        pacmanU[1] = pacman1U;
        pacmanU[2] = pacman2U;
        pacmanD[0] = pacman0;
        pacmanD[1] = pacman1D;
        pacmanD[2] = pacman2D;
        pacmanL[0] = pacman0;
        pacmanL[1] = pacman1L;
        pacmanL[2] = pacman2L;
        pacmanR[0] = pacman0;
        pacmanR[1] = pacman1R;
        pacmanR[2] = pacman2R;

        pacmanDeath1 = sheet.crop(2, 727, n1, n1);
        pacmanDeath2 = sheet.crop(62, 727, n1, n1);
        pacmanDeath3 = sheet.crop(122, 727, n1, n1);
        pacmanDeath4 = sheet.crop(182, 727, n1, n1);
        pacmanDeath5 = sheet.crop(242, 727, n1, n1);
        pacmanDeath6 = sheet.crop(302, 727, n1, n1);
        pacmanDeath7 = sheet.crop(362, 727, n1, n1);
        pacmanDeath8 = sheet.crop(422, 727, n1, n1);
        pacmanDeath9 = sheet.crop(482, 727, n1, n1);
        pacmanDeath10 = sheet.crop(542, 727, n1, n1);
        pacmanDeath11 = sheet.crop(602, 727, n1, n1);

        pacmanDeath[0] = pacmanDeath1;
        pacmanDeath[1] = pacmanDeath2;
        pacmanDeath[2] = pacmanDeath3;
        pacmanDeath[3] = pacmanDeath4;
        pacmanDeath[4] = pacmanDeath5;
        pacmanDeath[5] = pacmanDeath6;
        pacmanDeath[6] = pacmanDeath7;
        pacmanDeath[7] = pacmanDeath8;
        pacmanDeath[8] = pacmanDeath9;
        pacmanDeath[9] = pacmanDeath10;
        pacmanDeath[10] = pacmanDeath11;

        blinky1U = sheet.crop(3, 243, n1, n1);
        blinky2U = sheet.crop(63, 243, n1, n1);
        blinky1D = sheet.crop(123, 243, n1, n1);
        blinky2D = sheet.crop(183, 243, n1, n1);
        blinky1L = sheet.crop(243, 243, n1, n1);
        blinky2L = sheet.crop(303, 243, n1, n1);
        blinky1R = sheet.crop(363, 243, n1, n1);
        blinky2R = sheet.crop(423, 243, n1, n1);
        blinkyU[0] = blinky1U;
        blinkyU[1] = blinky2U;
        blinkyD[0] = blinky1D;
        blinkyD[1] = blinky2D;
        blinkyL[0] = blinky1L;
        blinkyL[1] = blinky2L;
        blinkyR[0] = blinky1R;
        blinkyR[1] = blinky2R;

        pinky1U = sheet.crop(3, 303, n1, n1);
        pinky2U = sheet.crop(63, 303, n1, n1);
        pinky1D = sheet.crop(123, 303, n1, n1);
        pinky2D = sheet.crop(183, 303, n1, n1);
        pinky1L = sheet.crop(243, 303, n1, n1);
        pinky2L = sheet.crop(303, 303, n1, n1);
        pinky1R = sheet.crop(363, 303, n1, n1);
        pinky2R = sheet.crop(423, 303, n1, n1);
        pinkyU[0] = pinky1U;
        pinkyU[1] = pinky2U;
        pinkyD[0] = pinky1D;
        pinkyD[1] = pinky2D;
        pinkyL[0] = pinky1L;
        pinkyL[1] = pinky2L;
        pinkyR[0] = pinky1R;
        pinkyR[1] = pinky2R;

        inky1U = sheet.crop(3, 363, n1, n1);
        inky2U = sheet.crop(63, 363, n1, n1);
        inky1D = sheet.crop(123, 363, n1, n1);
        inky2D = sheet.crop(183, 363, n1, n1);
        inky1L = sheet.crop(243, 363, n1, n1);
        inky2L = sheet.crop(303, 363, n1, n1);
        inky1R = sheet.crop(363, 363, n1, n1);
        inky2R = sheet.crop(423, 363, n1, n1);
        inkyU[0] = inky1U;
        inkyU[1] = inky2U;
        inkyD[0] = inky1D;
        inkyD[1] = inky2D;
        inkyL[0] = inky1L;
        inkyL[1] = inky2L;
        inkyR[0] = inky1R;
        inkyR[1] = inky2R;

        clyde1U = sheet.crop(3, 423, n1, n1);
        clyde2U = sheet.crop(63, 423, n1, n1);
        clyde1D = sheet.crop(123, 423, n1, n1);
        clyde2D = sheet.crop(183, 423, n1, n1);
        clyde1L = sheet.crop(243, 423, n1, n1);
        clyde2L = sheet.crop(303, 423, n1, n1);
        clyde1R = sheet.crop(363, 423, n1, n1);
        clyde2R = sheet.crop(423, 423, n1, n1);
        clydeU[0] = clyde1U;
        clydeU[1] = clyde2U;
        clydeD[0] = clyde1D;
        clydeD[1] = clyde2D;
        clydeL[0] = clyde1L;
        clydeL[1] = clyde2L;
        clydeR[0] = clyde1R;
        clydeR[1] = clyde2R;

        freightened1B = sheet.crop(3, 483, n1, n1);
        freightened2B = sheet.crop(63, 483, n1, n1);
        freightened1W = sheet.crop(123, 483, n1, n1);
        freightened2W = sheet.crop(183, 483, n1, n1);
        freightenedB[0] = freightened1B;
        freightenedB[1] = freightened2B;
        freightenedBW[0] = freightened1B;
        freightenedBW[1] = freightened2B;
        freightenedBW[2] = freightened1W;
        freightenedBW[3] = freightened2W;

        eatenU = sheet.crop(3, 603, n1, n1);
        eatenD = sheet.crop(63, 603, n1, n1);
        eatenL = sheet.crop(123, 603, n1, n1);
        eatenR = sheet.crop(183, 603, n1, n1);

        zero = sheet.crop(33, 540, n2, n2);
        one = sheet.crop(63, 540, n2, n2);
        two = sheet.crop(93, 540, n2, n2);
        three = sheet.crop(123, 540, n2, n2);
        four = sheet.crop(153, 540, n2, n2);
        five = sheet.crop(183, 540, n2, n2);
        six = sheet.crop(213, 540, n2, n2);
        seven = sheet.crop(243, 540, n2, n2);
        eight = sheet.crop(273, 540, n2, n2);
        nine = sheet.crop(303, 540, n2, n2);

        twoHundred = sheet.crop(5, 674, 2*n2, n2);
        fourHundred = sheet.crop(65, 674, 2*n2, n2);
        eightHundred = sheet.crop(125, 674, 2*n2, n2);
        sixteenHundred = sheet.crop(182, 674, 50, n2);

        lives = sheet.crop(243, 481, n1, n1);

        cherry = sheet.crop(507, 483, n1, n1);
        strawberry = sheet.crop(507, 543, n1, n1);
        peach = sheet.crop(509, 603, n1, n1);
        apple = sheet.crop(507, 663, n1, n1);
        grapes = sheet.crop(629, 483, n1, n1);
        galaxian = sheet.crop(629, 545, n1, n1);
        bell = sheet.crop(627, 602, n1, n1);
        key = sheet.crop(629, 664, n1, n1);

        fruits[0] = cherry;
        fruits[1] = strawberry;
        fruits[2] = peach;
        fruits[3] = peach;
        fruits[4] = apple;
        fruits[5] = apple;
        fruits[6] = grapes;
        fruits[7] = grapes;
        fruits[8] = galaxian;
        fruits[9] = galaxian;
        fruits[10] = bell;
        fruits[11] = bell;
        fruits[12] = key;

        oneHundred = sheet.crop(500, 14, n3, n2);
        threeHundred = sheet.crop(498, 74, n3, n2);
        fiveHundred = sheet.crop(497, 134, n3, n2);
        sevenHundred = sheet.crop(498, 189, n3, n2);
        oneThousand = sheet.crop(502, 254, n3, n2);
        twoThousand = sheet.crop(499, 314, n3, n2);
        threeThousand = sheet.crop(499, 374, n3, n2);
        fiveThousand = sheet.crop(499, 431, n3, n2);

        fruitsScores[0] = oneHundred;
        fruitsScores[1] = threeHundred;
        fruitsScores[2] = fiveHundred;
        fruitsScores[3] = fiveHundred;
        fruitsScores[4] = sevenHundred;
        fruitsScores[5] = sevenHundred;
        fruitsScores[6] = oneThousand;
        fruitsScores[7] = oneThousand;
        fruitsScores[8] = twoThousand;
        fruitsScores[9] = twoThousand;
        fruitsScores[10] = threeThousand;
        fruitsScores[11] = threeThousand;
        fruitsScores[12] = fiveThousand;

        ready = sheet.crop(604, 1, 142, 24);
        gameOver = sheet.crop(34, 572, 241, 24);

        a = sheet3.crop(8, 60, n4, n4);
        b = sheet3.crop(8+8*(1), 60, n4, n4);
        c = sheet3.crop(8+8*(2), 60, n4, n4);
        d = sheet3.crop(8+8*(3), 60, n4, n4);
        e = sheet3.crop(8+8*(4), 60, n4, n4);
        f = sheet3.crop(8+8*(5), 60, n4, n4);
        g = sheet3.crop(8+8*(6), 60, n4, n4);
        h = sheet3.crop(8+8*(7), 60, n4, n4);
        i = sheet3.crop(8+8*(8), 60, n4, n4);
        j = sheet3.crop(8+8*(9), 60, n4, n4);
        k = sheet3.crop(8+8*(10), 60, n4, n4);
        l = sheet3.crop(8+8*(11), 60, n4, n4);
        m = sheet3.crop(8+8*(12), 60, n4, n4);
        n = sheet3.crop(8+8*(13), 60, n4, n4);
        o = sheet3.crop(8+8*(14), 60, n4, n4);
        p = sheet3.crop(0, 68, n4, n4);
        q = sheet3.crop(8*(1), 68, n4, n4);
        r = sheet3.crop(8*(2), 68, n4, n4);
        s = sheet3.crop(8*(3), 68, n4, n4);
        t = sheet3.crop(8*(4), 68, n4, n4);
        u = sheet3.crop(8*(5), 68, n4, n4);
        v = sheet3.crop(8*(6), 68, n4, n4);
        w = sheet3.crop(8*(7), 68, n4, n4);
        x = sheet3.crop(8*(8), 68, n4, n4);
        y = sheet3.crop(8*(9), 68, n4, n4);
        z = sheet3.crop(8*(10), 68, n4, n4);
        pointer = sheet3.crop(8+8*(11), 68, n4, n4);
        redPointer = sheet3.crop(8+8*(15), 60, n4, n4);

    }
    
}
